name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Helsinki
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_languages: yes
          plugin_repositories: yes
          plugin_repositories_featured: prompt-master, color-logger, aoc2021, xmas-py
          plugin_repositories_order: starred
          plugin_stars: yes

